### ISSUE TITLE
What is the API of SML to SecsMessage?

### ISSUE THREAD

**Issue by sunyuanfeng1** [tornadoSemi/HsmsCpp#1]
I have found the API: GetSML.It converts the SecsMessage to the SML string.
Now I want the inverse transformation.Thank you for your help!

**Comment by tornadoSemi** [comment]
不支持反转。转sml只为日志使用。使用sml转secsmessage 效率不高。



发自我的小米手机
在 sunyuanfeng1 <notifications@github.com>，2021年3月10日 09:50写道：

I have found the API: GetSML.It converts the SecsMessage to the SML string.
Now I want the inverse transformation.Thank you for your help!

**Comment by sunyuanfeng1** [comment]
> 不支持反转。转sml只为日志使用。使用sml转secsmessage 效率不高。
那在实际应用中，客户端如果向设备发消息，不是应该先编辑统一SML语言吗，这一步应该是少不了呀

> 不支持反转。转sml只为日志使用。使用sml转secsmessage 效率不高。

那在实际应用中，客户端如果向设备发消息，不是应该先编辑统一SML语言吗，这一步应该是少不了呀

**Comment by sunyuanfeng1** [comment]
> 不支持反转。转sml只为日志使用。使用sml转secsmessage 效率不高。

那在实际应用中，客户端如果向设备发消息，不是应该先编辑统一SML语言吗，这一步应该是少不了呀

**Comment by tornadoSemi** [comment]
不用，直接编辑secs message就好，可以看下demo代码里，怎么做的。



发自我的小米手机
在 sunyuanfeng1 ***@***.***>，2021年3月11日 09:32写道：

不支持反转。转sml只为日志使用。使用sml转secsmessage 效率不高。

那在实际应用中，客户端如果向设备发消息，不是应该先编辑统一SML语言吗，这一步应该是少不了呀

**Comment by sunyuanfeng1** [comment]
> 不支持反转。转sml只为日志使用。使用sml转secsmessage 效率不高。 那在实际应用中，客户端如果向设备发消息，不是应该先编辑统一SML语言吗，这一步应该是少不了呀
> 不用，直接编辑secs message就好，可以看下demo代码里，怎么做的。

感谢你的解答。其实我的意思是从客户的角度要发送消息，那只能编辑sml，不能改代码；那我自己尝试写一个解析接口吧
