### ISSUE TITLE
请问Message类里的MID变量代表什么呢？

### ISSUE THREAD

**Issue by sunyuanfeng1** [tornadoSemi/HsmsCpp#3]

**Comment by tornadoSemi** [comment]
MID = Message ID.   ( System Bytes ).  ref. SEMI E4, SEMI E5, SEMI E37 .

**Comment by sunyuanfeng1** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tornadoSemi/HsmsCpp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 下午3:12
***@***.***&gt;;
抄送:&nbsp;"More ***@***.******@***.***&gt;;
主题:&nbsp;Re: [tornadoSemi/HsmsCpp] 请问Message类里的MID变量代表什么呢？ (#3)





 
MID = Message ID.   ( System Bytes ).  ref. SEMI E4, SEMI E5, SEMI E37 .
