### ISSUE TITLE
License Error.

### ISSUE THREAD

**Issue by lishem12** [tornadoSemi/HsmsCpp#4]
我这边想用SECSI 打开程序后弹出 
Open Port : COM1
Open Port OK: COM1
License Error.
为什么？我需要什么License？

**Comment by lishem12** [comment]
从你这里购买么？

**Comment by tornadoSemi** [comment]
是的，从我这里购买。

**Comment by tornadoSemi** [comment]
发邮件详谈 tornadocean@outlook.com

**Comment by moonmoonCL** [comment]
License Error影响使用吗？  我测试了下， 发现可以 使用
