### ISSUE TITLE
请问为什么使用别的仿真软件连接时，ip设为127.0.0.1可以连接，设为本机ip地址就连不上了呢？

### ISSUE THREAD

**Issue by sunyuanfeng1** [tornadoSemi/HsmsCpp#5]
先设为PASSIVE状态启动，然后用另一个仿真软件连接。防火墙什么的都关了啊。

**Comment by sunyuanfeng1** [comment]
ACTIVE模式是可以和其他ip设备正常连接的，但是PASSIVE就不行，这是为什么呢

**Comment by tornadoSemi** [comment]
PASSIVE 模式查看一下localIP，可以不写或写"0.0.0.0"

**Comment by sunyuanfeng1** [comment]
调了半天，是那个仿真软件更新版本了，旧版本有问题😂跟代码没关系



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月3日(周四) 晚上11:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tornadoSemi/HsmsCpp] 请问为什么使用别的仿真软件连接时，ip设为127.0.0.1可以连接，设为本机ip地址就连不上了呢？ (#5)




 
PASSIVE 模式查看一下localIP，可以不写或写"0.0.0.0"
